site_name: Fermentrack
repo_url: https://github.com/thorrak/fermentrack
repo_name: fermentrack
theme: readthedocs
pages:
  - Home: 'index.md'
  - FAQ: 'faq.md'
  - Install:
    - 'Index': 'install/index.md'
    - 'Raspberry Pi Setup': 'install/Raspi Setup.md'
    - 'Manual Installation': 'install/manual.md'
    - 'Legacy (Apache/PHP) App Support': 'install/Apache and PHP Support.md'
  - Configuration:
    - 'Configuration': 'config/config.md'
    - 'Flashing a Controller': 'config/Flashing a Controller.md'
    - 'Serial Controller Guided Setup': 'config/Serial Controller Setup.md'
    - 'WiFi Controller Guided Setup': 'config/WiFi Controller Setup.md'
    - 'Advanced (Manual) Controller Setup': 'config/Advanced Controller Setup.md'
  - Hardware:
    - 'Index': 'hardware/index.md'
    - 'ESP8266': 'hardware/ESP8266.md'
    - 'Arduino': 'hardware/Arduino.md'
    - 'Native Python (Fuscus)': 'hardware/Native Python.md'
    - 'Spark Core': 'hardware/Spark.md'
  - About:
    - 'Architecture': 'about/architecture.md'
    - 'Contribute': 'about/contribute.md'
    - 'Changelog': 'about/changelog.md'
    - 'License': 'about/license.md'
    - 'Included Components': 'about/components.md'
  - Develop:
    - 'Index': 'develop/index.md'
    - 'Models': 'develop/models.md'
