site_name: BrewPi Django Edition
repo_url: https://github.com/thorrak/brewpi-django
repo_name: brewpi-django
theme: readthedocs
pages:
  - Home: 'index.md'
  - Install:
    - 'Raspberry Pi Automated Installation': 'install/automated.md'
    - 'Manual Installation': 'install/manual.md'
  - Configuration:
    - 'Configuration': 'config/config.md'
  - Hardware:
    - 'Index': 'hardware/index.md'
    - 'ESP8266': 'hardware/ESP8266-2.md'
    - 'Arduino': 'hardware/Arduino.md'
    - 'Native Python (Fuscus)': 'hardware/Native Python.md'
    - 'Spark Core': 'hardware/Spark.md'
  - About:
    - 'Contribute': 'about/contribute.md'
    - 'Changelog': 'about/changelog.md'
    - 'License': 'about/license.md'
    
